### PR TITLE
Fix for macOS 12

### PR DESCRIPTION
**Pull request by cxa**

### CODE REVIEW

**Comment by lccambiaghi** [comment]
Hi, could you please merge this? I just upgraded to Monterey and spacebar unfortunately broke for me. Would be great to get a release on `nixpkgs`

**Comment by SultanSGillani** [comment]
Can we get this merged? The spacebar is worthless right now on macos 12

**Comment by SultanSGillani** [comment]
For anyone that does not want to wait you can follow instructions here: https://github.com/cmacrae/spacebar/issues/94#issuecomment-987758238

**Comment by cmacrae** [comment]
Sorry for the delay on this, everyone. Recent events in my personal life have left me unmotivated/unable to focus on projects.  
I've included @cxa's fix in the latest release - thank you very much :)

**Comment by SultanSGillani** [comment]
> Sorry for the delay on this, everyone. Recent events in my personal life have left me unmotivated/unable to focus on projects. I've included @cxa's fix in the latest release - thank you very much :)

Thanks. Sorry to hear that and hope things work out. Your work has been greatly appreciated.

**Pull request merged**
